"""add_crawl_fields_to_documents

Revision ID: ed5813e7dda5
Revises: a8a126bd0975
Create Date: 2025-07-04 02:02:57.306202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5813e7dda5'
down_revision = 'a8a126bd0975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('crawl_depth', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('crawl_task_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('crawl_metadata', sa.JSON(), nullable=True))
    op.create_index('idx_documents_crawl_task_id', 'documents', ['crawl_task_id'], unique=False)
    op.create_index('idx_documents_namespace_source', 'documents', ['namespace', 'source_type'], unique=False)
    op.create_index('idx_documents_source_type', 'documents', ['source_type'], unique=False)
    op.create_index('idx_documents_source_url', 'documents', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_source_url', table_name='documents')
    op.drop_index('idx_documents_source_type', table_name='documents')
    op.drop_index('idx_documents_namespace_source', table_name='documents')
    op.drop_index('idx_documents_crawl_task_id', table_name='documents')
    op.drop_column('documents', 'crawl_metadata')
    op.drop_column('documents', 'crawl_task_id')
    op.drop_column('documents', 'crawl_depth')
    # ### end Alembic commands ### 