"""Initial database schema

Revision ID: a8a126bd0975
Revises: 
Create Date: 2025-06-23 13:22:15.532681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a126bd0975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_message', sa.Text(), nullable=False),
    sa.Column('sources_used', sa.JSON(), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_created_at', 'chat_history', ['created_at'], unique=False)
    op.create_index('idx_chat_namespace', 'chat_history', ['namespace'], unique=False)
    op.create_index('idx_chat_session_id', 'chat_history', ['session_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_is_active', 'documents', ['is_active'], unique=False)
    op.create_index('idx_documents_namespace', 'documents', ['namespace'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index('idx_chunks_chunk_index', 'document_chunks', ['chunk_index'], unique=False)
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_vector_id', 'document_chunks', ['vector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_vector_id', table_name='document_chunks')
    op.drop_index('idx_chunks_document_id', table_name='document_chunks')
    op.drop_index('idx_chunks_chunk_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_documents_namespace', table_name='documents')
    op.drop_index('idx_documents_is_active', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_index('idx_documents_content_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_chat_session_id', table_name='chat_history')
    op.drop_index('idx_chat_namespace', table_name='chat_history')
    op.drop_index('idx_chat_created_at', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ### 